FROM ruby:2.5

RUN apt-get update && apt-get install -y \
  build-essential \
  nodejs

WORKDIR /tmp
ADD Gemfile* ./

RUN gem install bundler && bundle install --jobs 20 --retry 5

ENV PROJECT_ROOT /usr/src/app
COPY . $PROJECT_ROOT
WORKDIR $PROJECT_ROOT

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
