FROM ruby:2.5

RUN apt-get update && apt-get install -y \
  build-essential \
  nodejs

ENV PROJECT_ROOT /usr/src/app
WORKDIR $PROJECT_ROOT

ADD Gemfile* ./

RUN gem install bundler && bundle install --jobs 20 --retry 5

EXPOSE 3000

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
