FROM ruby:2.5

ENV PROJECT_ROOT /usr/src/app

ENV BUNDLE_JOBS=2 \
    BUNDLE_APP_CONFIG=$APP_HOME/.bundle \
    BUNDLE_PATH=$PROJECT_ROOT/vendor/bundle

ENV BUNDLE_DISABLE_SHARED_GEMS=true \

ENV PATH=$BUNDLE_PATH/bin:$PATH

RUN apt-get update && apt-get install -y \
  build-essential \
  nodejs

WORKDIR $PROJECT_ROOT
